CREATE DATABASE DB_PERSONAS;

USE DB_PERSONAS;

CREATE TABLE TBL_PERSONAS(
	ID INT IDENTITY PRIMARY KEY,
	NOMBRE NVARCHAR(50),
	EDAD INT,
	EMAIL NVARCHAR(150)
)

ALTER PROCEDURE SP_INSERTAPERSONA(
  @P_NOMBRE NVARCHAR(50) ,
  @P_EDAD INT ,
  @P_EMAIL NVARCHAR(50) 
)
AS 
BEGIN
	INSERT INTO TBL_PERSONAS(NOMBRE, EDAD, EMAIL) VALUES(@P_NOMBRE, @P_EDAD, @P_EMAIL);

END;

alter PROCEDURE SP_OBTIENEPERSONA(
  @P_ID INT
)
AS 
BEGIN
	IF(@P_ID IS NULL)  
		SELECT NOMBRE, EDAD, EMAIL, ID  FROM TBL_PERSONAS;
	ELSE 
		SELECT NOMBRE, EDAD, EMAIL, ID FROM TBL_PERSONAS WHERE ID = @P_ID;
END;